#!/bin/bash

$1 $2
linha1=$(wc -l < $1)
linha2=$(wc -l < $2)

if [ $linha1 -lt $linha2 ];
then
   echo "$1 é menor que $2!"
elif [ $linha2 -lt $linha1 ]
then
   echo "$1 é maior que $2!"
elif [ $linha1 -eq $linha2 ]
then
   echo "$1 é igual a $2!"
fi
