#!/bin/bash
$1 $2
if [ -e $1 ]; then
	a=$( cat ${1} | wc -l )
	if [ $a -lt $2 ]; then
	echo "Falha: O arquivo $1  possui apenas $a linhas"
	exit 1	
	else
		cat $1  | grep $2
		exit 1
		
	fi

else
echo "Arquivo Nao existe"
exit 1
fi
