#!/bin/bash 

echo 'O shell permite que se criem variáveis e que se lhes atribuam valores guardados durante a execução do shell. As variáveis podem ser variáveis locais ou variáveis de ambiente (globais). Os nomes das variáveis podem ser constituídos de quaisquer caracteres alfanumericos. Para criar e ao mesmo tempo atribuir um valor à variável na mesma operação, usamos o comando set para variáveis locais ou setenv para as de ambiente[*]. No caso do setenv não é usado o sinal de = entre o nome e o valor da variável. O valor de uma variável é acessado através do nome da variável precedido pelo operador $[*], por exemplo

$ set Universidade= "IFPB"

$ echo $Universidade

IFPB

Neste caso o echo mostra o conteúdo de $Universidade na tela. Note que o argumento passado para o echo é ""IFPB"" pois o shell já fez a interpolação da variável $estado na cadeia de caracteres correspondente. As variáveis podem ser usadas em qualquer comando no contexto do shell. Para referir-se ao nome de uma variável sem ambiguidade, inclue-se seu nome entre chaves { } , observe

$ set arquivos= "/dados/curso"

$ cp ${arquivos}/aula2.tex /home/alunos

'
