#!/bin/bash
read -p "Digite o Diretorio: " x 
	    if [ -e $x ]; then
		sed -E -i 's/^([0-9]{2})([0-9])([0-9]{4})([0-9]{4})$/(\1) \2 \3-\4/' $x
		
		exit 1
	   
	   else
		echo "Diretorio  Nao Existe"
		exit 1
		fi 
