#!/bin/bash
read -p "Digite dois numeros:  " n1 n2
maior() {
	(( $n1 >= $n2 )) && echo $n1 || echo $n2
}
maior $n1 $n2
read -p "Digite dois numeros:  " n3 n4
menor() {
	(( $n3 <= $n4 )) && echo $n3 || echo $n4
}
menor $n3 $n4
