#!/bin/bash

echo -e "a - Remover todas as maiúsculas
b - Remover todos os dígitos
c - Substituir caracteres especiais por <?>\n"

read -p "Digite sua opção: " opt

case $opt in
  "a"|"A") 
  "b"|"B") read -p "Digite o Arquivo " x 
	   if [ -e $x ]; then    
	    
	    sed -i  's/[0-9]\+//g' $x 
	     exit 1
	   
	   else
		echo "Arquivo  Nao Existe"
		exit 1
		fi ;;
  "c"|"C") 
esac
