#!/bin/bash


function maior {
NUM=$*
MAIOR=$1
for i in `echo $NUM`;
do
if [ $i -gt $MAIOR ];
then
MAIOR=$i
fi
done

echo "O maior número é '$MAIOR'"
}


function menor {
NUM2=$*
MENOR=$1
for r in `echo $NUM2`;
do
if [ $r -lt $MENOR ];
then
MENOR=$r
fi
done

echo "O menor  número é '$MENOR'" 

}

 maior  $*
 menor  $*
