#!/usr/bin/awk -f
{
	acc  = 0;
	
	for ( i=l; i<=NF; i++ )
	{
	  if ( $i ~ /[0-9]+/ ) acc = acc+$i;
	
	}
media=acc/3.0;
if (media >= 70) ap++;
else rp++;
if (media  <= 9.9) a++;
else if (media >= 10 && media <= 19.9) b++;
else if (media >= 20 && media <= 29.9) c++;
else if (media >= 30 && media <= 39.9) d++;
else if (media >= 40 && media <= 49.9) e++;
else if (media >= 50 && media <= 59.9) f++;
else if (media >= 60 && media <= 69.9) g++;
else if (media >= 70 && media <= 79.9) h++;
else if (media >= 80 && media <= 89.9) j++;
else if (media >= 90 && media <= 100) m++;


}
END {
print "Aprovados: "  ap
print "Reprovados: " rp 

print ""
print " Histograma "
print " Notas  0 - 9.9 = " a
print " Notas  10 - 19.9 = " b
print " Notas  20 - 29.9 = " c
print " Notas  30 - 39.9 = " d
print " Notas  40 - 49.9 = " e
print " Notas  50 - 59.9 = " f
print " Notas  60 - 69.9 = " g
print " Notas  70 - 79.9 = " h
print " Notas  80 - 89.9 = " j
print " Notas  90 - 100 = " m

}
